### ISSUE TITLE
Empty lines in Cascades are not supported

### ISSUE THREAD

**Issue by tom95** [hpi-swa-teaching/poppy-print#15]
As an example see most baselines:

```smalltalk
spec
    baseline: 'abc' with: [];
    baseline: 'def' with: [];
    
    package: 'abc';
    package: 'def'
```

**Comment by LinqLover** [comment]
Interesting, none of my baselines looks like this. I would always repeat the cascade receiver at the beginning of each cascade unit which I personally find better to read. But if this is a convention, preserving these newlines would probably not hurt. :-)

**Comment by tom95** [comment]
It's a pattern I use quite frequently, especially in the DSL-like areas, such as Baselines, UI building or configurations that work via message sends (example: https://github.com/tom95/sandblocks/blob/master/packages/Sandblocks-Core/SBTextInputMapping.class.st#L21).

You're correct that repeating the receiver is always an option here. In the general case, this necessitates a refactoring rather than just a reformatting though, e.g. introducing a temp var. We could of course also push for this by not supporting empty lines in cascades. I'll have to think about it for a bit, I guess :D

**Comment by LinqLover** [comment]
Fair point. While I don't use this style myself, a good pretty-printer should not get in the way. :-)

**Comment by LinqLover** [comment]
Just a kind note: If you could close these issues with a short notice (for instance: implemented/rejected/duplicate), this would be interesting for me and probably other watchers of this repository. :-)

**Comment by treyfel** [comment]
Sounds good. Will do so in the future! We Implemented this feature.

**Comment by LinqLover** [comment]
Yahoo, this is great to hear! :-)
