### ISSUE TITLE
Format on Save

### ISSUE THREAD

**Issue by CR1337** [hpi-swa-teaching/poppy-print#22]
Estimated 5 pts

**Comment by LinqLover** [comment]
FYI, there is already a working proposal for this in the Squeak Trunk which is currently being discussed, see: [[squeak-dev] The Inbox: Tools-ct.1054.mcz](http://forum.world.st/The-Inbox-Tools-ct-1054-mcz-td5129527.html)

You can load the patch into your image by opening a Monticello Browser from the Tools menu, choosing the **inbox** repository, navigating to the **Tools** package, selecting the `Tools-ct.1054` version, and pressing **merge.**

**Comment by LinqLover** [comment]
@tom95 As far as I understand, with your approach, it won't be possible any longer to compile an ugly-printed method into a class even when using the manual way through the compiling interface on `ClassDescription`. The only way to circumvent this will then be to turn off the preference. Do you think this could be a problem? Could there be any scenarios in which we would want any kind of code generator, for instance, to compile methods in their custom formatting? For example, this *might* affect squeak-graphics-opengl (but I'm not closely involved in this project). Another (hypothetical) example could be a tool that inserts a certain marker in the source code of an auto-generated method. If PoppyPrint repeatedly broke this marker by reformatting it in a way the other tool does not expect, this would be fatal, too.
