### ISSUE TITLE
Label lines for non-formatting

### ISSUE THREAD

**Issue by tiny-fish-T** [hpi-swa-teaching/poppy-print#28]
As a user, I want to label certain code lines for non-formatting because I want to keep intentional formatting AND format the rest of my code with poppy-print,

**Comment by LinqLover** [comment]
Has this been implemented or discarded? :-)

**Comment by CR1337** [comment]
> Has this been implemented or discarded? :-)

It has been implemented and was pushed to dev branch :)

**Comment by LinqLover** [comment]
Great to hear that!
