### ISSUE TITLE
Bug with testAllMethods

### ISSUE THREAD

**Issue by JessicaDierking** [hpi-swa-teaching/poppy-print#41]
When executing testAllMethods the method StrikeFont class >> dejaVuSansBold12Form leads to an endless loop

**Comment by JessicaDierking** [comment]
Poppy-Printing the test itself also doesn't work

**Comment by treyfel** [comment]
This is not really an issue as it doesn't lead to an endless loop but rather it takes very long to format certain methods, that contain large data arrays.
