### ISSUE TITLE
Increase timeout from Tests

### ISSUE THREAD

**Issue by Yannis-Hofmann** [hpi-swa-teaching/poppy-print#48]
## Summary
The test `testAllMethods` can sometimes run longer than the set timeout, so the test fails sometime, if it takes too long

## Steps to reproduce

- run the `testAllMethods` Test multiple times 

### current behavior

- the test fails randomly sometimes

### expected behavior

- the test runs through all the time

## Possible fixes

already implemented in the Release branch

- [x] set timeout for method `testAllMethod` to `120s`

**Comment by kdauer** [comment]
60s seemed to low so an increase to 120s seems appropriate
