### ISSUE TITLE
set row length to standard browser window

### ISSUE THREAD

**Issue by kdauer** [hpi-swa-teaching/poppy-print#49]
### Problem to solve

As `Squeak Developer`, I want `PoppyPrint to not print lines longer than the width of the standard browser window` so that `I can  see the entire code`.

#### Further details

relates to #36 
[image](https://user-images.githubusercontent.com/80156619/121327796-109a2b00-c914-11eb-85ae-1337df331d5b.png)

-The width of a String s using the Font f can be computed by:
```smalltalk
f widthOfString: s
```
-standard browser window has a width of 588 px

### Acceptance Criteria
- [ ]  When Squeak is opened up and the Browser Window is opened in standard size. Given `the standard browser window`, when `Poppyprint is formatting`, then `the code is formatted for the standard window size`

**Comment by AlexanderUngefug** [comment]
How to get the pixel width of a String.
Example:

TextStyle default defaultFont widthOfString: 'Hallo' 70
