### ISSUE TITLE
Custom style option to enable a dot at the end of a method

### ISSUE THREAD

**Issue by AlexanderUngefug** [hpi-swa-teaching/poppy-print#63]
### Problem to solve

As `Squeak Enthusiast`, I want `to have the option to enable a dot at the end of a method`.

### Proposal

- [ ]

### Testing

- [ ] 

### Acceptance Criteria

- [ ] When I format a method with poppyprint, depending on my style settings, I would like to have a dot/no dot at the end of this method.

**Comment by EnnioEnnio** [comment]
Interesting Idea, I just want to add that a dot '.' in Smalltalk contrary to the Semicolon ';' in C is intended as an expression seperator, not a terminator. A dot at the end of a return to me leads this concept ad absurdum.

**Comment by LinqLover** [comment]
Maybe also discuss the difference between final expressions vs. final return statements. For instance, a common coding style would be:

```smalltalk
self doThis.
self doThat.
```

but:

```smalltalk
self doThis.
^ self doThat
```

:-)

**Comment by EnnioEnnio** [comment]
@LinqLover Isn't this because there is always an implied return self at the end? To me this would totally align with the "dot as a separator" philosophy since the statement, even the final one, needs to be separated from the implicit return whereas the explicitly written return is in fact the last one so no separation is needed?

**Comment by LinqLover** [comment]
Yes, this is a popular argument. 🙂 Some, however, never want to write a dot after the last statement. It's all a matter of personal preferences ... maybe you can support all variants by the end of the semester. For this story, I would suggest appending a point to every statement that does not return.

**Comment by LinqLover** [comment]
Setting enabled:

```
self doThis.
self doThat.
```

```
self doThis.
^ self doThat
```

Setting disabled:

```
self doThis.
self doThat
```

```
self doThis.
^ self doThat
```
